### ISSUE TITLE
证书连不上

### ISSUE THREAD

**Issue by MAOGE555** [p1d3er/RemoteWebScreen#1]
证书有问题，怎么配置都连不上。
![image](https://github.com/p1d3er/RemoteWebScreen/assets/56222406/cb1bca3b-cdf9-4424-81f7-98699edf76e0)

**Comment by p1d3er** [comment]
双击安装到当前用户输入密码选个人，访问的时候加启动端口，如果是80端口就访问http://ip:80/:80
