### ISSUE TITLE
win7环境会报错

### ISSUE THREAD

**Issue by Burden-xy** [p1d3er/RemoteWebScreen#3]
![image](https://github.com/p1d3er/RemoteWebScreen/assets/30802818/b814c59e-cd63-40ea-a84a-ce8dbc9d2866)

**Comment by p1d3er** [comment]
可以正常监控吗

**Comment by Burden-xy** [comment]
> 可以正常监控吗

会直接退出

**Comment by p1d3er** [comment]
好的清明回来排查一下

**Comment by p1d3er** [comment]
> > 可以正常监控吗
> 
> 会直接退出

好的清明回来 排查一下

**Comment by p1d3er** [comment]
> > > 可以正常监控吗
> > 
> > 
> > 会直接退出
> 
> 好的清明回来 排查一下

目前本地测试未出问题，看报错是你本地`kernel32.dll`文件的问题
