### ISSUE TITLE
win7安装证书提示密码不对

### ISSUE THREAD

**Issue by klmyssn** [p1d3er/RemoteWebScreen#6]
![image](https://github.com/p1d3er/RemoteWebScreen/assets/37890522/6d388cab-e994-4013-a6db-cc3c58b48b0b)
密码不是RemoteWebScreen 吗？

**Comment by p1d3er** [comment]
> ![image](https://private-user-images.githubusercontent.com/37890522/344853033-6d388cab-e994-4013-a6db-cc3c58b48b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDY0NDMsIm5iZiI6MTcxOTkwNjE0MywicGF0aCI6Ii8zNzg5MDUyMi8zNDQ4NTMwMzMtNmQzODhjYWItZTk5NC00MDEzLWE2ZGItY2MzYzU4YjQ4YjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU5Y2QxY2NiYmI2ZWIzMmFhYTY5NGU3NmQ5MDUwMDJhZjYwZDBlYjQyNDc4MGY5YjM5ODU5YmU2MTcxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.su9jSCu513Apz_H17Bb0MGz5qp6I-HKB1-ZL4En-CIM) 密码不是RemoteWebScreen 吗？

是的，多试几次，经常会出这种问题

**Comment by klmyssn** [comment]
> > ![image](https://private-user-images.githubusercontent.com/37890522/344853033-6d388cab-e994-4013-a6db-cc3c58b48b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDY0NDMsIm5iZiI6MTcxOTkwNjE0MywicGF0aCI6Ii8zNzg5MDUyMi8zNDQ4NTMwMzMtNmQzODhjYWItZTk5NC00MDEzLWE2ZGItY2MzYzU4YjQ4YjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU5Y2QxY2NiYmI2ZWIzMmFhYTY5NGU3NmQ5MDUwMDJhZjYwZDBlYjQyNDc4MGY5YjM5ODU5YmU2MTcxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.su9jSCu513Apz_H17Bb0MGz5qp6I-HKB1-ZL4En-CIM) 密码不是RemoteWebScreen 吗？
> 
> 是的，多试几次，经常会出这种问题

好的，我试试，谢谢师傅

**Comment by klmyssn** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/37890522/344853033-6d388cab-e994-4013-a6db-cc3c58b48b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDY0NDMsIm5iZiI6MTcxOTkwNjE0MywicGF0aCI6Ii8zNzg5MDUyMi8zNDQ4NTMwMzMtNmQzODhjYWItZTk5NC00MDEzLWE2ZGItY2MzYzU4YjQ4YjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YTU5Y2QxY2NiYmI2ZWIzMmFhYTY5NGU3NmQ5MDUwMDJhZjYwZDBlYjQyNDc4MGY5YjM5ODU5YmU2MTcxYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.su9jSCu513Apz_H17Bb0MGz5qp6I-HKB1-ZL4En-CIM) 密码不是RemoteWebScreen 吗？
> > > 
> > > 
> > > 是的，多试几次，经常会出这种问题
> > 
> > 
> > 好的，我试试，谢谢师傅
> 
> 确实有这个问题 我还不知道怎么解决，win 10 正常，本机用WIN 7的 很少了吧

好吧，有的目标运维机器确实比较老，用的win7
