### ISSUE TITLE
能否直接在命令行直接安装证书，不需要点击安装

### ISSUE THREAD

**Issue by klmyssn** [p1d3er/RemoteWebScreen#7]
在一些项目环境里面，可能需要直接通过命令行静默安装，不通过双击，可以实现吗

**Comment by p1d3er** [comment]
> 在一些项目环境里面，可能需要直接通过命令行静默安装，不通过双击，可以实现吗

可以搜一下证书是否可以，证书是统一的

**Comment by klmyssn** [comment]
好的，我试试，谢谢。
